---
abstract: 'An Application to interface with http://rosettacode.org'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.96
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RosettaCode
requires:
  App::Cmd::Setup: 0
  IO::All: 0
  MediaWiki::Bot: 0
  Mo: 0
  Module::Pluggable: 0
  YAML::XS: 0
  constant: 0
  perl: v5.14.0
  utf8: 0
resources:
  homepage: https://github.com/ingydotnet/rosettacode-pm
  repository: https://github.com/ingydotnet/rosettacode-pm.git
version: 0.0.5
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.012
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Filter/CheckExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Filter/PruneCruft'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Filter/ManifestSkip'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Filter/MetaYAML'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Filter/License'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Filter/Readme'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Filter/ExecDir'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Filter/ShareDir'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Filter/MakeMaker'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Filter/Manifest'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Filter/TestRelease'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Filter/ConfirmRelease'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Filter/UploadToCPAN'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.012
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Filter/ReadmeFromPod'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Test::Compile'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Filter/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.012
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.012
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.012
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.012
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300033
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300033
